# Default values for mern-stack.

replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

frontend:
  image: "iammanjyot/mern-app-cluster:mern-frontend"
  containerPort: 3000
  servicePort: 3000
  nodePort: 32000
  environment:
    REACT_APP_BACKEND_URL: "http://backend-service:5000"

backend:
  image: "iammanjyot/mern-app-cluster:mern-backend"
  containerPort: 5000
  servicePort: 5000
  environment:
    MONGO_HOST: "mongodb-service"
    MONGO_PORT: "27017"
    MONGO_USERNAME: "manjyotsinghchaudhary"
    MONGO_PASSWORD: "Xs7AnsL6bDfhirvy"

mongodb:
  image: "mongo:6.0"
  containerPort: "27017"
  storage: "5Gi"
  secret:
    username: "manjyotsinghchaudhary"
    password: "Xs7AnsL6bDfhirvy"
