apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bWFuanlvdHNpbmdoY2hhdWRoYXJ5
  mongo-password: WHM3QW5zTDZiRGZoaXJ2eQ==
  mongo-uri: bW9uZ29kYitzcnY6Ly9tYW5qeW90c2luZ2hjaGF1ZGhhcnk6WHM3QW5zTDZiRGZoaXJ2eUB0cmF2ZWxiYWNrZW5kLnFjeXp2Lm1vbmdvZGIubmV0Lw==
